# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Persistence Issues
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jlapolla

# Build settings
markdown: kramdown

# Serving
host: 0.0.0.0
port: 8080

# Collections
collections:
  objects:
    output: true
  figures:
    output: true

# Object defaults
defaults:
  -
    scope:
      path: ""
      type: objects
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: figures
    values:
      layout: "figure"

